
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atxtojnnwookypaqapvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0eHRvam5ud29va3lwYXFhcHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDkxMDMsImV4cCI6MjA2MDIyNTEwM30.vkqWH5oGI1EDpKJlVBb_fPcetiLBnBge9UZuxhem2eY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
